# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

http:
  cors_allowed_origins:
    - "http://192.168.0.139"
    - "http://127.0.0.1"
    - "http://localhost"


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
